on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

      - name: checkout
        uses: actions/checkout@v2

      - name: Add 'approved' label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: approved
